# Generated by Django 4.2.7 on 2025-10-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
